
import java.sql.ResultSet;
import java.sql.SQLException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sarmo01
 */
public class KontaktlistaJFrame extends javax.swing.JFrame {
    
     FileManager list = new FileManager(); 
     DbManager db = new DbManager();
     //int räknare = 0;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KontaktlistaJFrame.class.getName());

    /**
     * Creates new form KontaktlistaJFrame
     */
    public KontaktlistaJFrame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtnGroup = new javax.swing.ButtonGroup();
        btnTaBort = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnSpara = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tbxEfternamn = new javax.swing.JTextField();
        rbtnFörnamn = new javax.swing.JRadioButton();
        rbtnEfternamn = new javax.swing.JRadioButton();
        tbxFörnamn = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textA = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        tbxTelefonnummer = new javax.swing.JTextField();
        btnLäggTill = new javax.swing.JButton();
        btnHämta = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txfDelete = new javax.swing.JTextField();

        btnTaBort.setText("ta bort kontakt");

        jButton1.setText("jButton1");

        btnSpara.setText("Spara");
        btnSpara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparaActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Förnamn");

        jLabel2.setText("Efternamn");

        rbtnGroup.add(rbtnFörnamn);
        rbtnFörnamn.setSelected(true);
        rbtnFörnamn.setText("Förnamn först");
        rbtnFörnamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnFörnamnActionPerformed(evt);
            }
        });

        rbtnGroup.add(rbtnEfternamn);
        rbtnEfternamn.setText("Efternamn först");
        rbtnEfternamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnEfternamnActionPerformed(evt);
            }
        });

        textA.setColumns(20);
        textA.setRows(5);
        jScrollPane1.setViewportView(textA);

        jLabel3.setText("Telefon");

        btnLäggTill.setText("Lägg till");
        btnLäggTill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLäggTillActionPerformed(evt);
            }
        });

        btnHämta.setText("Hämta");
        btnHämta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHämtaActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        txfDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(rbtnFörnamn)
                .addGap(18, 18, 18)
                .addComponent(rbtnEfternamn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txfDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tbxFörnamn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tbxTelefonnummer, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(109, 109, 109)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbxEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLäggTill, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addComponent(btnHämta)
                        .addContainerGap(57, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(tbxEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbxFörnamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tbxTelefonnummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLäggTill)
                    .addComponent(btnHämta))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnFörnamn)
                    .addComponent(rbtnEfternamn)
                    .addComponent(btnDelete)
                    .addComponent(txfDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnEfternamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnEfternamnActionPerformed
        // TODO add your handling code here:
         this.textA.setText("");             // tömmer textarean
         skrivUtEfternamn();
         
    }//GEN-LAST:event_rbtnEfternamnActionPerformed

    private void btnLäggTillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLäggTillActionPerformed
        // TODO add your handling code here:
        String förnamn = this.tbxFörnamn.getText(); // läser av textboxen
        this.tbxFörnamn.setText("");                // tömmer textboxen
        String efternamn = this.tbxEfternamn.getText();
        this.tbxEfternamn.setText("");
        String telefonnummer = this.tbxTelefonnummer.getText();
        this.tbxTelefonnummer.setText("");
        
        
        if(förnamn.contentEquals("")&&efternamn.contentEquals("")&&telefonnummer.contentEquals("")){        // skapar ingen kontakt om alla textboxar är tomma 
        }
        else{
            Kontakt kon = new Kontakt(förnamn,efternamn,telefonnummer); // skapar ny kontakt
            db.insert(kon);
             
        if(rbtnFörnamn.isSelected()){ // om förnamn först är vald
            skrivUtFörnamn();
        }else{ 
            skrivUtEfternamn();
                }
        }
        
    }//GEN-LAST:event_btnLäggTillActionPerformed

    private void rbtnFörnamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnFörnamnActionPerformed
        // TODO add your handling code here:
        this.textA.setText("");             // tömmer textarean
        skrivUtFörnamn();
        
    }//GEN-LAST:event_rbtnFörnamnActionPerformed

    private void btnHämtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHämtaActionPerformed
        // TODO add your handling code here:
        //konList = FileManager.readFromFile(); //hämtar
        //this.textA.setText("");  
        if(rbtnFörnamn.isSelected()){ // om förnamn först är vald
            skrivUtFörnamn();
        }else{ 
            skrivUtEfternamn();
                }
        
       
    }//GEN-LAST:event_btnHämtaActionPerformed

    private void btnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaActionPerformed
        // TODO add your handling code here:
        //list.saveToFile(konList); //sparar
    }//GEN-LAST:event_btnSparaActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String idText = txfDelete.getText();
        int id = Integer.valueOf(idText);
        
        db.delete(id);
        
         if(rbtnFörnamn.isSelected()){ // om förnamn först är vald
            skrivUtFörnamn();
        }else{ 
            skrivUtEfternamn();
                }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txfDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new KontaktlistaJFrame().setVisible(true));
    }
    
    private void skrivUtFörnamn(){
        this.textA.setText("");
        ResultSet rs = db.getAllData();
          if (rs != null) {
            try {
                while (rs.next()) {
                    this.textA.append(rs.getInt("kontaktid") + "\t"
                            + rs.getString("firstname") + "\t"
                            + rs.getString("lastname") + "\t"
                            + rs.getString("phonenumber") + "\n");
                }
            } catch (SQLException ex) {
                System.out.println("Ingen data.");
            }
        } else {
              System.out.println("Ingen data från databasen, kontrollera anslutningen.");
        }

    }
    private void skrivUtEfternamn(){
        this.textA.setText("");
        
        ResultSet rs = db.getAllData();
          if (rs != null) {
            try {
                while (rs.next()) {
                    this.textA.append(rs.getInt("kontaktid") + "\t"
                            + rs.getString("lastname") + "\t"
                            + rs.getString("firstname") + "\t"
                            + rs.getString("phonenumber") + "\n");
                }
            } catch (SQLException ex) {
                System.out.println("Ingen data.");
            }
        } else {
              System.out.println("Ingen data från databasen, kontrollera anslutningen.");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnHämta;
    private javax.swing.JButton btnLäggTill;
    private javax.swing.JButton btnSpara;
    private javax.swing.JButton btnTaBort;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtnEfternamn;
    private javax.swing.JRadioButton rbtnFörnamn;
    private javax.swing.ButtonGroup rbtnGroup;
    private javax.swing.JTextField tbxEfternamn;
    private javax.swing.JTextField tbxFörnamn;
    private javax.swing.JTextField tbxTelefonnummer;
    private javax.swing.JTextArea textA;
    private javax.swing.JTextField txfDelete;
    // End of variables declaration//GEN-END:variables
}
